os: linux
dist: bionic

# env:
# - CHANGE_MINIKUBE_NONE_USER=true

before_script:
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube
  - sudo mkdir -p /usr/local/bin/
  - sudo install minikube /usr/local/bin/

script:
  - minikube version
