os: linux
dist: bionic

services:
  - docker

before_script:
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube
  - sudo mkdir -p /usr/local/bin/
  - sudo install minikube /usr/local/bin/

script:
  - minikube version
  - minikube start # --driver=docker
  - minikube status
